@extends('admin.layout')
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <a class="closethis">Close</a>
                <header>
                    <h2 class="heading">Export List</h2>
                </header>
                <div class="contents" >
                    <table id="example" class="display" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <td>Start Date</td>
                            <td>End Date</td>
                            <td>Food</td>
                            <td>Country</td>
                            <td>Quantity</td>
                            <td>Price</td>
                            <td>Location</td>

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($importAll as $import)
                            <tr>
                                <td>{{ $import->start_date }}</td>
                                <td>{{ $import->end_date }}</td>
                                <td>{{ $import->Food->name }}</td>
                                <td>{{ $import->Country->name }}</td>
                                <td>{{ $import->quantity }} {{ $import->Unit->name }}</td>
                                <td>{{ $import->price }}</td>
                                <td>{{ $import->Location->name }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div></div></div></div>
@endsection
@section('extraJs')
    {!! HTML::script('assets/js/jquery.dataTables.js') !!}
    {!! HTML::script('assets/js/dataTables.tableTools.js') !!}
    {!! HTML::style('assets/css/jquery.dataTables.css') !!}
    {!! HTML::style('assets/css/dataTables.tableTools.css') !!}
    <script type="text/javascript" language="javascript" class="init">
        $(document).ready( function () {
            $('#example').dataTable( {
                "sDom": 'T<"clear">lfrtip',
                "oTableTools": {
                    "aButtons": [
                        {
                            "sExtends": "print",
                            "sMessage": "<span>Generated by DataTables</span>"
                        },
                        {

                            "sExtends": "csv",
                            "sMessage": "<span>Generated by DataTables</span>"
                        },
                        {
                            "sExtends": "xls",
                            "sMessage": "<span>Generated by DataTables</span>"
                        },

                        {
                            "sExtends": "copy",
                            "sMessage": "<span>Generated by DataTables</span>"
                        },

                        {
                            "sExtends": "pdf",
                            "sMessage": "<span>Generated by DataTables</span>"
                        },
                    ]
                }
            } );
        } );
    </script>
@endsection
@section('extraCss')
    <style>
        #example_wrapper{
            margin-top: 2%;
        }
    </style>
@endsection