@extends('admin.layout')
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <a class="closethis">Close</a>
                <header>
                    <h2 class="heading">Location</h2>
                    {{--<a href="" class="btn btn-primary">Add Location</a>--}}
                </header>
                <div class="contents" >
                    {!! Form::open(array('url' => "admin/location", 'id' => 'location')) !!}
                    <div class="table-box">
                        <table class="table" style="border: 0 !important;">
                            <thead>
                            <tr>
                                <th class="col-md-4">Location</th>
                                <td class="col-md-8">
                                    <input class="form-control2" name="name" required="">
                                    &nbsp; <label class="redtext">*</label>
                                </td>
                            </tr>
                            <tr>
                                <th class="col-md-4"></th>
                                <td class="col-md-2">
                                    <button type="submit" class="btn btn-success style2">Create</button>
                                </td>
                            </tr>
                            </thead>
                        </table>
                    </div>
                    {!! Form::close() !!}

                    <table id="example" class="display" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <td>#</td>
                            <td>Location</td>
                            <td>Action</td>

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($allLocation as $key=>$location)
                            <tr>
                                <td>
                                    {{ $key+1 }}</td>
                                <td>{{ $location->name }}</td>
                                <td>
                                    <a href='{!! URL::to("admin/location/$location->id/edit") !!}' class="btn-primary">Update</a>
                                    <a onclick="return confirm('Are you sure you want to delete this item?');" href='{!! URL::to("admin/location/$location->id/delete") !!}' class="btn-primary">Delete</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div></div></div></div>
@endsection
@section('extraJs')
    {!! HTML::script('assets/js/jquery.dataTables.js') !!}
    {!! HTML::script('assets/js/dataTables.tableTools.js') !!}
    {!! HTML::style('assets/css/jquery.dataTables.css') !!}
    {!! HTML::style('assets/css/dataTables.tableTools.css') !!}
    <script type="text/javascript" language="javascript" class="init">
        $(document).ready( function () {
            $("#location").submit(function(event) {
                event.preventDefault();
                var values = $("#location").serialize();
                $.ajax({
                    url: '{!! URL::to("admin/location") !!}',
                    type: "POST",
                    data: values,
                    cache: false,
                    beforeSend: function(){
                        $('#loader').html('<img src="{{ URL::to('assets/images/loader_gif.gif') }}" style="height: 100px;">');
                    },
                    success: function(data) {
                        $('#loader').hide();
                        if(data=='true') {
                            window.location.href = "{!! URL::to('admin/location') !!}";
                        }else{
                            new PNotify({
                                title: 'ERROR',
                                text: data,
                                type: 'error',
                                delay: 3000
                            });
                        }
                    }
                });
            });
            $('#example').dataTable( {
                "sDom": 'T<"clear">lfrtip',
                /*"oTableTools": {
                 "aButtons": [
                 {
                 "sExtends": "print",
                 "sMessage": "<span>Generated by DataTables</span>"
                 },
                 {

                 "sExtends": "csv",
                 "sMessage": "<span>Generated by DataTables</span>"
                 },
                 {
                 "sExtends": "xls",
                 "sMessage": "<span>Generated by DataTables</span>"
                 },

                 {
                 "sExtends": "copy",
                 "sMessage": "<span>Generated by DataTables</span>"
                 },

                 {
                 "sExtends": "pdf",
                 "sMessage": "<span>Generated by DataTables</span>"
                 },
                 ]
                 }*/
            } );
        } );
    </script>
@endsection
@section('extraCss')
    <style>
        #example_wrapper{
            margin-top: 2%;
        }
    </style>
@endsection